### ISSUE TITLE
No entity condition on the take power

### ISSUE THREAD

**Issue by Com2486** [ThDilos/Realistic-Fox-Origin#1]
You can take items from ANY mob. Not just foxes. This means you can also take from villagers, breaking their trades. Skeletons drop their bows, wither skeletons drop their swords. Unless this is intended, please add an entity condition.

**Comment by Com2486** [comment]
Here's a video outlining the issue, with a simple fix in the description!
https://youtu.be/nE9LlGtWnkw

**Comment by ThDilos** [comment]
Thanks for pointing out! 
Fixed in V2.1
