### ISSUE TITLE
Data pack version?

### ISSUE THREAD

**Issue by TheVengefulSpirit** [ThDilos/Realistic-Fox-Origin#3]
Heya, I can't seem to get forge to recognise it as a mod. I have added the dependency needed and it still doesn't seem to see it...

If ya can, are you able to provide a data pack for it? I can't seem to find one along side the jar in your releases... 

Thank you! <3

**Comment by ThDilos** [comment]
Done!
You can find the uploaded datapacks here:
[1.19.4-1.20.x](https://github.com/ThDilos/Realistic-Fox-Origin/blob/main/ThDilos.Fox.Origin_V3.6_1.19.4-1.20.x.zip)
[1.19-1.19.3](https://github.com/ThDilos/Realistic-Fox-Origin/blob/main/ThDilos.Fox.Origin_V3.6_1.19-1.19.3.zip)
[1.18.2](https://github.com/ThDilos/Realistic-Fox-Origin/blob/main/ThDilos.Fox.Origin_V3.6_1.18.2.zip)

**Comment by TheVengefulSpirit** [comment]
Thank you so much!

Would you also happen to have one for your extra fox mod? It looked really interesting and I thought it was cool!

Would the firefox in that pack also happen to be finished?

**Comment by ThDilos** [comment]
That mod only supports 1.20.1, I haven't done any backward porting.

Uploaded here
[Datapack](https://github.com/ThDilos/UnRealistic-Fox-Origin/blob/main/ThDilos.Fox.Expanded_V1.6_1.20.1_Datapack.zip)
[ResourcePack](https://github.com/ThDilos/UnRealistic-Fox-Origin/blob/main/ThDilos.Fox.Expanded_V1.6_1.20.1_ResourcePack.zip)

The firefox is not yet finished, but soon will be ;)

**Comment by TheVengefulSpirit** [comment]
Don't worry, I'm using 1.20.1!

Thank you so much though and thank you for responding so soon!
