### ISSUE TITLE
request: allow wearing armor above iron

### ISSUE THREAD

**Issue by TheBearodactyl** [ThDilos/Realistic-Fox-Origin#7]
maybe instead just give weakness and slowness when wearing any armor above iron?

**Comment by ThDilos** [comment]
Tbf that was my initial idea, 

then I thought this origin really need some nerfs, considering how they can one-shot most mobs in game.

But on second thoughts, this just makes netherite'n stuff less valuable to them, and people has been complaining about armor restriction.

I may change it to apply slowness and weakness in next version yeah.

Thanks for the feedback!

**Comment by TheBearodactyl** [comment]
> Tbf that was my initial idea,
> 
> then I thought this origin really need some nerfs, considering how they can one-shot most mobs in game.
> 
> But on second thoughts, this just makes netherite'n stuff less valuable to them, and people has been complaining about armor restriction.
> 
> I may change it to apply slowness and weakness in next version yeah.
> 
> Thanks for the feedback!

np :D
