### ISSUE TITLE
[Bug] sleep mod on seat/ride

### ISSUE THREAD

**Issue by PengWanYT** [ThDilos/Realistic-Fox-Origin#9]
**Versions**
**Minecraft Version: 1.21.1
**ModLoader & its Version: fabric Loader/ latest
**Origins Mod Version: 1.13.0 - alpha 10
**Fox Origin Version: 4.1.0

**Describe the bug**
A fox sleep mod that make you noclip into void when seat/ride minecar and animal.

**To Reproduce**
When you sit on minecar or animal, then go in sleep mode will make you noclip fast in void.

**Expected behavior**
When update fox origin mod, then I am playing normal, until when I am ride minecar, it's was long way to go so was take break, then the auto sleep mode make me noclip under void very fast, when I am go creative mod to do again, it's still make me noclip void when in sleep mode on ride.

**Screenshots / Videos**
I am will post it on edit

**Comment by ThDilos** [comment]
This Origin cannot run in Origins 1.13.0 - Alpha.10 (The latest publish) currently, only Alpha.9 from last month.
I'm trying to port it to Alpha.10 now but.. there are quite a few existing bugs that straight up make the Fox Origin unplayable
(Including Pouncing in wrong direction / Sleeping Fox disappear etc.)
I have reported these abnormalities to the Modder, maybe they'll publish a fixed version soon.

**Comment by PengWanYT** [comment]
> This Origin cannot run in Origins 1.13.0 - Alpha.10 (The latest publish) currently, only Alpha.9 from last month. I'm trying to port it to Alpha.10 now but.. there are quite a few existing bugs that straight up make the Fox Origin unplayable (Including Pouncing in wrong direction / Sleeping Fox disappear etc.) I have reported these abnormalities to the Modder, maybe they'll publish a fixed version soon.

Oohhh, that why.... guess only can use alpha 9 mod :00
Oh well your mod is good anyway 👍
